#!/bin/bash

# Load environment variables from all files in bin/lib/*
for FILE in bin/lib/*; do
  set -a
  # this routine ranges through a folder of files that we don't explicitly know (@davidsneighbour)
  # see https://github.com/koalaman/shellcheck/wiki/SC1090
  # shellcheck source=/dev/null
  source "${FILE}"
  set +a
done

# Load environment variables from .env file if it exists
source_env() {
  if [ -f .env ]; then
    # shellcheck source=/dev/null
    source .env
  fi
}
source_env

usage() {
  echo "Usage: $0 <directory>..."
  exit 1
}

if [ $# -lt 1 ]; then
  usage
fi

script_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
conversion_file="$script_directory/aliases.toml"

if [ ! -f "$conversion_file" ]; then
  echo "Conversion file '$conversion_file' not found."
  exit 1
fi

# Expand the glob patterns
eval "set -- $@"

# Loop through each provided directory
for directory in "$@"; do
  if [ ! -d "$directory" ]; then
    echo "Directory '$directory' not found."
    continue
  fi

  while IFS='=' read -r search_string replace_string; do
    search_string=$(echo "$search_string" | tr -d '[:space:]' | tr -d '-')
    replace_string=$(echo "$replace_string" | tr -d '[:space:]' | tr -d '"' | tr -d '-')

    find "$directory" -type f -exec sed -i -E "s/(\s|\(|\{)($search_string)(\s|\)|\})/\1$replace_string\3/g" {} +

    echo "Replaced '$search_string' with '$replace_string' in $directory"
  done <"$conversion_file"
done

echo "Replacement complete."
