#!/bin/bash
REQUIRED_TOOLS=(
  hugo
  npm
)

for TOOL in "${REQUIRED_TOOLS[@]}"; do
  if ! command -v "${TOOL}" >/dev/null; then
    echo "${TOOL} is required... "
    exit 1
  fi
done

# build website
npm run build:hugo
npm run build:pagefind

# cleaning up
rm -f index.json
rm -f links.json
